### ISSUE TITLE
Using the plugin on Android project

### ISSUE THREAD

**Issue by chemouna** [tableau/gradle-test-timeout#2]
Hello, 

thanks for the plugin, I tried using the plugin with android project:
i keep getting 
`Task with name 'compileTestJava' not found in project`

tried configuring the compile task name with 
```
testTimeoutPolicy {
        testDebugUnitTest {
            timeout = 30
            timeoutUnits = 'SECONDS'
            compileTestTaskName = "compileDebugUnitTestKotlin"
        }
 }
```
but keep getting the same error, any pointers ?

Thanks

**Comment by roastario** [comment]
have you applied the 'java' plugin to your project? this task is usually generated by this plugin.
